// Role-based permissions system
export const ROLES = {
  SUPREME_ADMIN: 'supreme_admin',
  STORE_OWNER: 'store_owner',
  STORE_MANAGER: 'store_manager',
  EMPLOYEE_INVENTORY: 'employee_inventory',
  EMPLOYEE_FULFILLMENT: 'employee_fulfillment',
  ARCHITECT_OWNER: 'architect_owner',
  SENIOR_ARCHITECT: 'senior_architect',
  JUNIOR_ARCHITECT: 'junior_architect',
  PROJECT_MANAGER: 'project_manager',
  CUSTOMER: 'customer',
} as const;

export const PERMISSIONS = {
  // Store permissions
  STORE_CREATE: 'store:create',
  STORE_READ: 'store:read',
  STORE_UPDATE: 'store:update',
  STORE_DELETE: 'store:delete',
  STORE_SUSPEND: 'store:suspend',
  
  // Product permissions
  PRODUCTS_CREATE: 'products:create',
  PRODUCTS_READ: 'products:read',
  PRODUCTS_UPDATE: 'products:update',
  PRODUCTS_DELETE: 'products:delete',
  
  // Order permissions
  ORDERS_READ: 'orders:read',
  ORDERS_UPDATE: 'orders:update',
  ORDERS_REFUND: 'orders:refund',
  
  // User permissions
  USERS_CREATE: 'users:create',
  USERS_READ: 'users:read',
  USERS_UPDATE: 'users:update',
  USERS_BAN: 'users:ban',
  
  // Financial permissions
  FINANCE_READ: 'finance:read',
  FINANCE_PAYOUT: 'finance:payout',
  FINANCE_COMMISSION: 'finance:commission',
  
  // AI permissions
  AI_MANAGE: 'ai:manage',
  AI_CREDITS: 'ai:credits',
  AI_ANALYTICS: 'ai:analytics',
  
  // Platform permissions
  PLATFORM_SETTINGS: 'platform:settings',
  PLATFORM_ANALYTICS: 'platform:analytics',
  PLATFORM_REPORTS: 'platform:reports',
  
  // Architecture permissions
  ARCHITECTURE_SERVICES_CREATE: 'architecture:services:create',
  ARCHITECTURE_SERVICES_READ: 'architecture:services:read',
  ARCHITECTURE_SERVICES_UPDATE: 'architecture:services:update',
  ARCHITECTURE_SERVICES_DELETE: 'architecture:services:delete',
  ARCHITECTURE_PROJECTS_READ: 'architecture:projects:read',
  ARCHITECTURE_PROJECTS_UPDATE: 'architecture:projects:update',
  ARCHITECTURE_PROPOSALS_CREATE: 'architecture:proposals:create',
  ARCHITECTURE_PROPOSALS_READ: 'architecture:proposals:read',
  ARCHITECTURE_PROPOSALS_UPDATE: 'architecture:proposals:update',
  ARCHITECTURE_PROPOSALS_DELETE: 'architecture:proposals:delete',
  ARCHITECTURE_PORTFOLIO_MANAGE: 'architecture:portfolio:manage',
  ARCHITECTURE_TEAM_MANAGE: 'architecture:team:manage',
} as const;

// Role permission mappings
export const ROLE_PERMISSIONS = {
  [ROLES.SUPREME_ADMIN]: [
    // All permissions
    ...Object.values(PERMISSIONS),
  ],
  
  [ROLES.STORE_OWNER]: [
    PERMISSIONS.STORE_READ,
    PERMISSIONS.STORE_UPDATE,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.PRODUCTS_DELETE,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.ORDERS_REFUND,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_PAYOUT,
    PERMISSIONS.AI_CREDITS,
    PERMISSIONS.AI_ANALYTICS,
  ],
  
  [ROLES.STORE_MANAGER]: [
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.USERS_READ,
  ],
  
  [ROLES.EMPLOYEE_INVENTORY]: [
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.ORDERS_READ,
  ],
  
  [ROLES.EMPLOYEE_FULFILLMENT]: [
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.PRODUCTS_READ,
  ],
  
  [ROLES.ARCHITECT_OWNER]: [
    PERMISSIONS.STORE_READ,
    PERMISSIONS.STORE_UPDATE,
    PERMISSIONS.ARCHITECTURE_SERVICES_CREATE,
    PERMISSIONS.ARCHITECTURE_SERVICES_READ,
    PERMISSIONS.ARCHITECTURE_SERVICES_UPDATE,
    PERMISSIONS.ARCHITECTURE_SERVICES_DELETE,
    PERMISSIONS.ARCHITECTURE_PROJECTS_READ,
    PERMISSIONS.ARCHITECTURE_PROJECTS_UPDATE,
    PERMISSIONS.ARCHITECTURE_PROPOSALS_CREATE,
    PERMISSIONS.ARCHITECTURE_PROPOSALS_READ,
    PERMISSIONS.ARCHITECTURE_PROPOSALS_UPDATE,
    PERMISSIONS.ARCHITECTURE_PROPOSALS_DELETE,
    PERMISSIONS.ARCHITECTURE_PORTFOLIO_MANAGE,
    PERMISSIONS.ARCHITECTURE_TEAM_MANAGE,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_PAYOUT,
  ],
  
  [ROLES.SENIOR_ARCHITECT]: [
    PERMISSIONS.ARCHITECTURE_SERVICES_CREATE,
    PERMISSIONS.ARCHITECTURE_SERVICES_READ,
    PERMISSIONS.ARCHITECTURE_SERVICES_UPDATE,
    PERMISSIONS.ARCHITECTURE_PROJECTS_READ,
    PERMISSIONS.ARCHITECTURE_PROJECTS_UPDATE,
    PERMISSIONS.ARCHITECTURE_PROPOSALS_CREATE,
    PERMISSIONS.ARCHITECTURE_PROPOSALS_READ,
    PERMISSIONS.ARCHITECTURE_PROPOSALS_UPDATE,
    PERMISSIONS.ARCHITECTURE_PORTFOLIO_MANAGE,
  ],
  
  [ROLES.JUNIOR_ARCHITECT]: [
    PERMISSIONS.ARCHITECTURE_SERVICES_READ,
    PERMISSIONS.ARCHITECTURE_PROJECTS_READ,
    PERMISSIONS.ARCHITECTURE_PROJECTS_UPDATE,
    PERMISSIONS.ARCHITECTURE_PROPOSALS_CREATE,
    PERMISSIONS.ARCHITECTURE_PROPOSALS_READ,
    PERMISSIONS.ARCHITECTURE_PROPOSALS_UPDATE,
  ],
  
  [ROLES.PROJECT_MANAGER]: [
    PERMISSIONS.ARCHITECTURE_PROJECTS_READ,
    PERMISSIONS.ARCHITECTURE_PROJECTS_UPDATE,
    PERMISSIONS.ARCHITECTURE_PROPOSALS_READ,
    PERMISSIONS.USERS_READ,
  ],
  
  [ROLES.CUSTOMER]: [
    // No admin permissions
  ],
};

export type Role = keyof typeof ROLE_PERMISSIONS;
export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];